name:    callumscode2
version: "0.2.0"

dependencies:
- aeson
- base
- blaze-html
- blaze-markup
- classy-prelude-yesod
- cmark
- directory
- fast-logger
- file-embed
- foreign-store
- hjsmin
- mime-mail
- mime-mail-ses
- monad-logger
- persistent
- persistent-sqlite
- persistent-template
- shakespeare
- tagsoup
- template-haskell
- text
- time
- wai
- wai-extra
- warp
- yaml
- yesod
- yesod-auth
- yesod-core
- yesod-form
- yesod-newsfeed
- yesod-static

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Wredundant-constraints
- -Wpartial-fields

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src
  when:
  - condition: (flag(dev)) || (flag(library-only))
    then:
      ghc-options:
      - -Wall
      - -O0
      cpp-options: -DDEVELOPMENT
    else:
      ghc-options:
      - -Wall
      - -O2

# Runnable executable for our application
executables:
  callumscode2:
    main: main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - callumscode2
    when:
    - condition: flag(library-only)
      buildable: false

# Test suite
tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - callumscode2
    - hspec
    - microlens
    - yesod-test

# Define flags used by "yesod devel" to make compilation faster
flags:
  library-only:
    description: Build for use with "yesod devel"
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false
