name:    callumscode2
version: "0.2.0"

dependencies:
- aeson >=0.6 && <1.4
- base >=4.9.1.0 && <5
- blaze-html >= 0.9.0.1 && < 0.10
- classy-prelude-yesod >=1.1 && < 1.5
- directory >=1.1 && <1.4
- fast-logger >=2.2 && <2.5
- file-embed
- foreign-store
- hjsmin >=0.1 && <0.3
- markdown >= 0.1.17 && < 0.2
- mime-mail >= 0.4.14 && < 0.5
- mime-mail-ses >= 0.4.1 && < 0.5
- monad-logger >=0.3 && <0.4
- persistent >=2.0 && <2.9
- persistent-sqlite >=2.6.2 && <2.9
- persistent-template >=2.0 && <2.9
- shakespeare >=2.0 && <2.1
- tagsoup >= 0.14 && < 1.0
- template-haskell
- text >=0.11 && <2.0
- time >= 1.8 && < 1.9
- wai >= 3.2.1 && < 3.3
- wai-extra >=3.0 && <3.1
- warp >=3.0 && <3.3
- yaml >=0.8 && <0.9
- yesod >=1.6 && <1.7
- yesod-auth >=1.6 && <1.7
- yesod-core >=1.6 && <1.7
- yesod-form >=1.6 && <1.7
- yesod-newsfeed >= 1.6 && < 1.7
- yesod-static >=1.6 && <1.7
- yesod-text-markdown >= 0.1.0 && < 0.2

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src
  when:
  - condition: (flag(dev)) || (flag(library-only))
    then:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O0
      cpp-options: -DDEVELOPMENT
    else:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O2

# Runnable executable for our application
executables:
  callumscode2:
    main: main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - callumscode2
    when:
    - condition: flag(library-only)
      buildable: false

# Test suite
tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - callumscode2
    - hspec >=2.0.0
    - yesod-test
    - microlens

# Define flags used by "yesod devel" to make compilation faster
flags:
  library-only:
    description: Build for use with "yesod devel"
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false
